### PR TITLE
added sabnzbd, sickrage and couchpotato via docker

### PR DESCRIPTION
**Pull request by shapetheLOLa**
I still know a lot people who prefer sabnzbd, couchpotato and sickrage over nzbget and sonarr, radarr. This will just lets them choose what they want to use. I've called the tag full_alt for now, but I'm open to better names

### CODE REVIEW

**Comment by desimaniac** [comment]
Thanks Jan! 

I have no issue with adding those containers, but I will need to tweak this a bit before I can accept it.

**Comment by shapetheLOLa** [comment]
Np, feel free to do so :-)

**Comment by shapetheLOLa** [comment]
sorry, my iphone went rogue, I didn't want to close this... :-)

**Comment by desimaniac** [comment]
I havent forgotten about this. I need to make changes to how we do download folders and make them a bit more generic ( vs app specific mount paths in Sonarr/Radarr) to allow for additional download clients.

**Comment by desimaniac** [comment]
Thanks. Also going to be making changes to tags, so when im ready ill let you know to rebase :p.

**Comment by shapetheLOLa** [comment]
ok :-) 👍

**Comment by cloudbitvps** [comment]
I just did exactly this manually, everything's working perfect 👍

**Comment by desimaniac** [comment]
Sab requires a few tweaks to config post install. Working on that now.

**Comment by cloudbitvps** [comment]
Excellent work mate

**Pull request closed without merging**
