### PR TITLE
Added support for Plexdrive 4

### PR DESCRIPTION
**Pull request by uberjew666**
I've tweaked the Plexdrive role to include the option for Plexdrive 4. I have had many problems using Plexdrive 5 on any machine with less than 16GB. Reading other users who faced similar issues, I migrated to Plexdrive 4 and found it to be much more stable.

The default version is 5, but those requiring version 4 can change this in settings.yml.default.

### CODE REVIEW

**Comment by desimaniac** [comment]
Thanks for the submission. 

Just a couple points here: 
1) We put PRs into develop branch not master;
2) I had already added an install choice for Plexdrive 4 into CB via the [feature mounts branch](https://github.com/Cloudbox/Cloudbox/tree/feature/mounts). That will soon be merged into develop branch and then master. If you need PD4 now, join the Discord server and there are instructions pinned on how to switch to that branch and migrate over.

**Comment by uberjew666** [comment]
Ah, I understand.
I can't seem to find where it is in the feature mounts branch however.

**Comment by desimaniac** [comment]
It's under the remote role. And it needs adv settings filled in.

**Comment by desimaniac** [comment]
Change  to main repo's vfs/mergerfs 
 
1. `cd ~/cloudbox`
2. `git fetch && git checkout feature/mounts`
3. `sudo ansible-playbook cloudbox.yml --tags settings`
4. `sudo nano adv_settings.yml`
4a. Edit the following:

```
mounts:
  unionfs: unionfs
  remote: plexdrive4
```
Note: if you had just `plexdrive`, in the remote field, it would automatically stitch to PD5 or PD4 depending on the ram (8GB or lower would go to PD4)
5. `sudo ansible-playbook cloudbox.yml --tags mounts`

**Comment by uberjew666** [comment]
Thanks @desimaniac, I've found it now.
I like the idea of it automatically selecting the correct version depending on memory resources. I considered doing something like this myself.

**Pull request closed without merging**
