### PR TITLE
Rclone VFS: Update for full cache mode

### PR DESCRIPTION
**Pull request by owine**
Requires rclone >=1.53

Credit to darthShadow for example parameters

### CODE REVIEW

**Comment by saltydk** [comment]
Not sure we should set full as the default let alone doing it without exposing the options.

**Comment by darthShadow** [comment]
Also, `--no-checksum` can be problematic with uploads in case some bad memory corrupts the data being uploaded. Not as much of a concern with downloads, however. So this should probably not be in the defaults for AIO setups where many people use consumer-grade memory with no ECC capabilities.

**Comment by saltydk** [comment]
Waiting a bit to merge this until the cache issues have been fixed. https://github.com/rclone/rclone/issues/4446

**Comment by saltydk** [comment]
Beta now includes a fix for the issue that I was waiting to get fixed. I'd still want a config option, at bare minimum, for the cache size before considering merging this.

**Comment by saltydk** [comment]
Since no work is being done on implementing this with an option of setting the cache mode or size I'm closing this.

**Pull request closed without merging**
