### PR TITLE
Use filter on label to only stop/start cloudbox managed containers

### PR DESCRIPTION
**Pull request by z3t**
Rather than start/stop all running containers when undertaking a Cloudbox maintenance task limit to Cloudbox managed containers by a label (com.github.cloudbox.cloudbox.managed_restart) added at container creation for all ansible roles .

I've considered a "Cloudbox maintenance task" as backup, feeder-mount, and feeder-dismount.

System maintenance tasks involving container start/stop actions, such as those within the docker ansible role still start/stop all running containers.

### CODE REVIEW

**Comment by desimaniac** [comment]
Well since most users are keeping their persistent data in /opt folder, isn't it prudent to stop all containers before doing a backup of /opt, to lower the risk of corruption?

**Comment by z3t** [comment]
What about applications accessing data in /opt that aren’t running within a docker container? That would even include roles in cloudbox like traktarr.

I believe you have sufficient caveats on the project wiki around unexpected experience if not used on a fresh install. In addition we could update the wiki with instructions on adding the label to user created containers bind mounting from /opt?

Or consider a larger and much more difficult to manage project change to move bond mounts out of the top level /opt?

**Comment by desimaniac** [comment]
Well Traktarr's db, i believe, is destroyed and rebuilt on each run, so not a big deal if it's running and trying to send api requests to Sonarr/Radarr, when those two are shutdown. I suspect Plex Autoscan's db is the same way. However, backup is already starting and stopping plexdrive / cloudplow services, so wouldnt be too much add in other CB related ones.

**Comment by desimaniac** [comment]
Anyways, let me get back to you on this.

**Comment by RXWatcher1** [comment]
I think this isn't something I'd be comfortable using. I have containers that are not part of CB that I'd need to also get backed up. I'm not going to write a script to bring those down separately to back them up. I think if your concern is that CB brings everything down then you should write your own backup routines specific to you. CB needs to follow the 80% rule and cover at least 80% of the users needs. I think the current process does that. One way I've been thinking about is btrfs snapshots. supposedly they can be done with sqlite and mariadb databases up. I don't know if I'm comfortable with that. I'd stop everything, snapshot, bring everything online, Mount snapshot and backup snapshot. you have to know your backups are solid otherwise they could be worthless when you need them the most.

**Comment by z3t** [comment]
There would be no need to write your own script, just apply the label to your own containers and they would be covered by the CB stop/start routine.

I would imagine >80% of CB users are likely not using any additional containers or at least ones that aren’t also bundled Ansible roles which would automatically be covered by this change.

Restarting all VMs breaks any non-disruptive coexistence with other containers under the assumption that they may be deliberately configured with the intent of being backed
up by CB without the user being able to follow instructions to explicitly demonstrate this.

If stop/restart all is indeed the preferred option could I suggest an adv_setting of say a Boolean LABEL_RESTART is made that conditionally toggles between this and stop/restart all?

**Comment by desimaniac** [comment]
Are you on discord?

**Comment by z3t** [comment]
Nope, could you fill me in on what I’ve missed out on?

**Comment by z3t** [comment]
There isn’t, the update process on the wiki describes a git pull and immediate reinstall which shouldn’t cause a problem as the backup isn’t required in any of the triggered playbooks.

Alternatively we could look at offering it as a different restart pattern triggered by an ansible when conditional as I described above? That way a user should only change the advanced setting if they know what they’re getting into.

**Comment by desimaniac** [comment]
The reason I mentioned the previous is because there will be people who will just 'git pull', and then their backups will run and then some/all of their containers wont be stopping since they would haven actually updated CB. It happens often. Ill just have to make an announcement to everyone on Discord to actually update CB post git pull. 

Also I added the changes in directly into develop. So no need for the PR. FYI, the git history has changed, so you might want to force reset all your forks.

**Pull request closed without merging**
