### PR TITLE
Add sickbeard_mp4_automator to Cloudbox

### PR DESCRIPTION
**Pull request by andrewkhunn**
I've successfully got [sickbeard_mp4_automator](https://github.com/mdhiggins/sickbeard_mp4_automator) integrated with Cloudbox. Here's what I've managed to get cobbled together so far, however, a few caveats:

1. Currently, sickbeard_mp4_automator needs to be installed before Sonarr(4k) and Radarr(4k) as I have been unable to figure out a way to stat if those containers exist so that `roles/sickbeard_mp4_automator/tasks/main.yml` can automagically install the dependencies into them
2. It would also be convenient if there were a way to script the output of `/opt/scripts/plex_autoscan/plex_autoscan_url.sh` into the approriate place in `/opt/scripts/sickbeard_mp4_automator/post_process/sickbeard_plex_autoscan.py`

If this is something you think you want included into Cloudbox, I'd be happy to work with you to get this pull request up to snuff and can also author some wiki entries for the configuration side of things. Also, please let me know if you have any questions.

Thanks!

### CODE REVIEW

**Comment by desimaniac** [comment]
Good work. 

As far as sonarr4k and radarr4k, you could check either the opt folder or get a list of installed/running containers and check if those are in there.

**Comment by desimaniac** [comment]
I've never used the mp4 automator before. Any setup guide you want to send would be helpful. I'd need to test it out before pushing anything up.

**Comment by andrewkhunn** [comment]
Sorry, I have been receiving your messages, just haven't had a ton of time this week to make any further progress.

Basically, the PR should be fully operational. Install sickbeard_mp4_automator and just rerun your sonarr and radarr tags (or manually execute the `docker exec` commands from the edits in their respective `main.yml`s) which will install the necessary required packages into their individual containers.

To enable mp4 conversion, all you need to do is change the plex_autoscan Connect script to only fire 'On Rename'. Then add a 'Custom Script' to fire ' On Download' and 'On Upgrade' and point it to either `/scripts/sickbeard_mp4_automator/postSonarr.py` or `/scripts/sickbeard_mp4_automator/postRadarr.py`. Finally, edit `/scripts/sickbeard_mp4_automator/autoProcess.ini.sample`, add your Sonarr and Radarr API keys in the appropriate sections, and save as `autoProcess.ini` and edit `/scripts/sickbeard_mp4_automator/post_process/sickbeard_plex_autoscan.py` and add your plex_autoscan URL.

- [Connect tab after implementation](https://imgur.com/0EKNhhC)
- [Custom Script dialog](https://imgur.com/nSx6if3)

This will now be the order of operations once a download is handed back to Sonarr/Radarr from NZBGet/ruTorrent:

1. Sonarr/Radarr renames the file and executes the sickbeard_mp4_automator Connect script
2. sickbeard_mp4_automator runs, converts the renamed file to an mp4 following the config in `autoProcess.ini`, and deletes the original
3. sickbeard_mp4_automator executes the `/scripts/sickbeard_mp4_automator/post_process/sickbeard_plex_autoscan.py` script notifying plex_autoscan to scan the new files' directory
4. sickbeard_mp4_automator notifies Sonarr/Radarr of the new filename and initiates a rescan of the file location to pick up the change

I've populated `autoProcess.ini` with some (what I think are) sane defaults. The only issues with the PR are ones I've already noted above. I will circle back around and get those last issues ironed out, but I won't have time until probably later on this upcoming week.

Let me know if you have any other questions. Also, I am 'Boethius' on Discord if you prefer that.

Thanks for all you do on this project!

**Comment by revotus** [comment]
Is this still active? I'm very new to docker and ansible and so while I could include the automator script in the sonarr and radarr containers like I did with [sonarr episode trimmer](https://gitlab.com/spoatacus/sonarr-episode-trimmer), I'd like to wait until the script can be included in its own container, which is over my head right now.

I have recently switched to cloudbox and I am very much loving it. I'd like to go through and update the quality on a lot of my shows, but want to wait for this addition first. Thanks, guys, great work.

**Comment by andrewkhunn** [comment]
I'll be submitting a new PR shortly which handles this integration a little more elegantly by linking to a modified hotio/suitarr image instead of the `docker exec` nonsense.

**Pull request closed without merging**
