### PR TITLE
add Gazee comic reader web app

### PR DESCRIPTION
**Pull request by zxvv**
This adds the Gazee comic reader web app:
https://github.com/hubbcaps/gazee

using the docker image:
https://hub.docker.com/r/linuxserver/gazee/

### CODE REVIEW

**Comment by zxvv** [comment]
By the way,  I'd be glad to create a pull request for these as well if there is any interest:
medusa
mylar
headphones
airsonic

**Comment by danjames92** [comment]
@zxvv I'd love airsonic / mylar 👍

**Comment by desimaniac** [comment]
Do you want to submit these to the [Community](https://github.com/Cloudbox/Community) project?

**Comment by desimaniac** [comment]
Ill close this PR for now since it's way outdated...

**Pull request closed without merging**
